"""Adiciona tabela mfa_recovery_codes

Revision ID: 7c84b59f63f7
Revises: cc0065610539
Create Date: 2025-10-23 16:07:39.710029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c84b59f63f7"
down_revision: Union[str, Sequence[str], None] = "cc0065610539"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mfa_recovery_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("hashed_code", sa.String(length=255), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mfa_recovery_codes_hashed_code",
        "mfa_recovery_codes",
        ["hashed_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_mfa_recovery_codes_id"), "mfa_recovery_codes", ["id"], unique=False
    )
    op.create_index(
        "ix_mfa_recovery_codes_user_id", "mfa_recovery_codes", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mfa_recovery_codes_user_id", table_name="mfa_recovery_codes")
    op.drop_index(op.f("ix_mfa_recovery_codes_id"), table_name="mfa_recovery_codes")
    op.drop_index("ix_mfa_recovery_codes_hashed_code", table_name="mfa_recovery_codes")
    op.drop_table("mfa_recovery_codes")
    # ### end Alembic commands ###
