"""adicionar_tabelas_oidc_client_e_code

Revision ID: 9ad96a26ae81
Revises: 5be083e42f0d
Create Date: 2025-10-24 09:16:33.195843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad96a26ae81'
down_revision: Union[str, Sequence[str], None] = '5be083e42f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth2_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=120), nullable=True),
    sa.Column('redirect_uris_str', sa.Text(), nullable=True),
    sa.Column('scope_str', sa.Text(), nullable=False),
    sa.Column('response_types_str', sa.Text(), nullable=False),
    sa.Column('grant_types_str', sa.Text(), nullable=False),
    sa.Column('token_endpoint_auth_method', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth2_clients_client_id'), 'oauth2_clients', ['client_id'], unique=True)
    op.create_table('oauth2_authorization_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=True),
    sa.Column('response_type', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('auth_time', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.String(length=120), nullable=True),
    sa.Column('code_challenge', sa.String(length=128), nullable=True),
    sa.Column('code_challenge_method', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth2_authorization_codes')
    op.drop_index(op.f('ix_oauth2_clients_client_id'), table_name='oauth2_clients')
    op.drop_table('oauth2_clients')
    # ### end Alembic commands ###
