"""adicionar_tabela_trusted_devices

Revision ID: 5be083e42f0d
Revises: d154b22ba7a0
Create Date: 2025-10-24 08:33:12.061804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be083e42f0d'
down_revision: Union[str, Sequence[str], None] = 'd154b22ba7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_devices_device_token_hash'), 'trusted_devices', ['device_token_hash'], unique=True)
    op.create_index(op.f('ix_trusted_devices_id'), 'trusted_devices', ['id'], unique=False)
    op.create_index('ix_trusted_devices_user_id', 'trusted_devices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trusted_devices_user_id', table_name='trusted_devices')
    op.drop_index(op.f('ix_trusted_devices_id'), table_name='trusted_devices')
    op.drop_index(op.f('ix_trusted_devices_device_token_hash'), table_name='trusted_devices')
    op.drop_table('trusted_devices')
    # ### end Alembic commands ###
