# .github/workflows/ci.yml
#
# Pipeline de CI (Continuous Integration) para a API de Autenticação Python
# Versão Profissional com Múltiplas Verificações

name: Python CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      
      - name: Lint with Ruff
        run: |
          ruff check .
          ruff format --check .

      # --- NOVAS ETAPAS DE VERIFICAÇÃO ---

      - name: Static Type Checking (MyPy)
        run: |
          # Verifica o código da aplicação por erros de tipo
          mypy app
      
      - name: Code Security Scan (Bandit)
        run: |
          # Roda o scan de segurança no código da aplicação (-r: recursivo)
          # -lll: Reporta apenas problemas de confiança ALTA (High)
          bandit -r app -lll
      
      - name: Dependency Security Scan (Safety)
        env:
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
        run: |
          # Usa 'safety check' (em vez de scan) com os flags '-i'
          # 'safety check' respeita os flags de ignore locais.
          safety check -r requirements.txt -i 64459 -i 64396
      
      # --- ETAPA DE TESTE ATUALIZADA ---
      
      - name: Run Pytest with Coverage
        run: |
          # Roda os testes, medindo a cobertura do diretório 'app'
          # Falha o build se a cobertura for menor que 80%
          pytest --cov=app --cov-report=term --cov-fail-under=80